export type ItslearningRestApiEntitiesPersonProfile = {
  PersonId: number;
  FirstName: string;
  LastName: string;
  FullName: string;
  Language: string;
  ProfileImageUrl: string;
  Children: Array<unknown>;
  iCalUrl: string;
  CanAccessMessageSystem: boolean;
  CanAccessCalendar: boolean;
  CanAccessPersonalSettings: boolean;
  CanAccessInstantMessageSystem: boolean;
  TimeZoneId: string;
  Use12HTimeFormat: boolean;
  SyncKey: string;
  CanAccessCourses: boolean;
  iCalFavoriteOnlyUrl: string;
  HasHigherEducationLanguage: boolean;
};
