import type { ItslearningRestApiEntitiesInstantMessageThreadType } from "../InstantMessageThreadType";
import type { EntityListOfItslearningRestApiEntitiesInstantMessage } from "./EntityListOfItslearning.RestApi.Entities.InstantMessage.ts";
import type { ItslearningRestApiEntitiesInstantMessage } from "./Itslearning.RestApi.Entities.InstantMessage.ts";
import type { ItslearningRestApiEntitiesInstantMessageMassMessageType } from "./Itslearning.RestApi.Entities.InstantMessageMassMessageType.ts";
import type { ItslearningRestApiEntitiesLocationRecipient } from "./Itslearning.RestApi.Entities.LocationRecipient.ts";
import type { ItslearningRestApiEntitiesThreadParticipant } from "./Itslearning.RestApi.Entities.ThreadParticipant.ts";

export type ItslearningRestApiEntitiesInstantMessageThread = {
	InstantMessageThreadId: number;
	Name: string;
	Created: Date;
	CreatedByTeacher: boolean;
	CreatedBy: number;
	Type: ItslearningRestApiEntitiesInstantMessageThreadType;
	ColorSchema: string;
	Messages: EntityListOfItslearningRestApiEntitiesInstantMessage;
	LastMessage: ItslearningRestApiEntitiesInstantMessage;
	MatchingMessageIds: number[];
	Participants: ItslearningRestApiEntitiesThreadParticipant[];
	ParticipantsCount: number;
	HasActiveParticipants: boolean;
	HasInactiveParticipants: boolean;
	NumberOfInactiveParticipants: number;
	InactiveParticipantFullName: string | null;
	HasCreatorInThread: boolean;
	IsCurrentUserARecipientWithSourceLocation: boolean;
	LocationRecipients: ItslearningRestApiEntitiesLocationRecipient[];
	CanShowParticipantsPage: boolean;
	LastReadInstantMessageId: number;
	SortIndex: number;
	OnlyThreadAdminCanSendToThread: boolean;
	IsThreadAdministrator: boolean;
	IsThreadModerator: boolean;
	InstantMessageLocationId: number;
	IsBlocked: boolean;
	UserAllowToBlockThread: boolean;
	IsAbuse: boolean;
	IsAbuseReportedByCurrentUser: boolean;
	MassMessageType: ItslearningRestApiEntitiesInstantMessageMassMessageType;
	Tooltip: string;
	CanDelete: boolean;
};
