# .github/workflows/publish.yml
name: Build and Publish npm Package

# Trigger the workflow on push to the main branch or when a new tag is created
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # For semantic version tags like v1.2.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version you need
          cache: "npm" # Enables caching for npm dependencies

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build
        run: npm run build # Adjust this if your build script has a different name

      # Step 5: Configure npm authentication
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 6: Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
