# .github/workflows/publish.yml
name: Build and Publish npm Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # For semantic version tags like v1.2.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Bun environment
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Build the project
      - name: Build
        run: bun run build

        # Step 5: Configure npm authentication
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 6: Publish to npm
      - name: Publish to npm
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
